favicon: /img/favicon.png
logo:
  html: <img src="/img/logo.gif" />
  style:
    width: auto
    height: 4rem
    border-radius: 50%;

nav:
  Home: /

# local search
# required: npm install hexo-generator-search
search: true

# wordcount
# required: npm install hexo-wordcount
wordcount:
  enable: true
  wordcount: true
  min2read: true
  total_wordcount: true

# article
post:
  # author avatar
  avatar: https://www.imlete.cn/img/avatar.png
  # article abstract
  abstract: 200
  # The default is the `date_format` and `time_format` fields in the hexo configuration file (_config.yml)
  date_format: # YYYY-MM-DD HH:mm:ss

open_graph:
  enable: true
  options: # config: https://hexo.io/docs/helpers#open-graph

# Code blocks theme
highlightTheme: default # default / darker / pale night / light / ocean / mac / mac light

footer:
  since: 2020
  custom: A clean and lightweight Hexo theme
