favicon: /img/favicon.png
logo:
  html: <img src="/img/logo.gif" />
  style:
    width: auto
    height: 4rem
    border-radius: 50%;

nav:
  Home: /
  About: /about/

# custom improt resouces
import:
  # reference `custom aside` config
  # support html
  head:
    before:
    after:
  body:
    before:
    after:

# local search
search:
  enable: true
  path: search.json
  field: post
  content: true

# image lazy load
lazyload:
  enable: true
  loding: /img/load.gif # image loading placeholder (defaults to 1px base64)

# wordcount
# required: npm install hexo-wordcount
wordcount:
  enable: true
  wordcount: true
  min2read: true
  total_wordcount: true

# article
post:
  # author avatar
  avatar: https://www.helloimg.com/i/2025/06/20/6854c956db28c.jpg
  # article abstract
  abstract: 200
  # The default is the `date_format` and `time_format` fields in the hexo configuration file (_config.yml)
  date_format: # YYYY-MM-DD HH:mm:ss
  copyright:
    enable: true
    # The default is the `title` fields in the hexo configuration file (_config.yml)
    title:
    # The default is the `author` fields in the hexo configuration file (_config.yml)
    author:
    # The default is the `url` fields in the hexo configuration file (_config.yml)
    # You can also write as email: mailto:xxx@gmail.com
    url:
    licenses: CC BY-NC-SA 4.0
    licenses_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
    description: All posts on this blog are licensed under the ${licenses} license unless otherwise stated. Please cite ${title} !

open_graph:
  enable: true
  options: # config: https://hexo.io/docs/helpers#open-graph

# Code blocks theme
highlight_theme: default # default / darker / pale night / light / ocean / mac / mac light

footer:
  since: 2025
  custom: Just a simple blog, powered by Hexo and mengd theme.

# 评论系统配置
comments:
  enable: true
  type: twikoo
  twikoo:
    envId: https://arcmeteor-blog.netlify.app/.netlify/functions/twikoo # 替换为你的腾讯云环境ID
    region: ap-shanghai # 可选，默认 ap-shanghai
    path: window.location.pathname # 可选，评论关联页面路径

# custom aside
aside:
  # support html
  before:
    - '<img src="/img/beside.gif" alt="雾雨魔理沙" style="width:100%;">'
  after: []